/// Build script: auto-discovers .test.npcs files and generates Rust tests.
///
/// Scans `tests/` (relative to project root) for `*.test.npcs` files
/// and generates `tests/generated_tests.rs` with one `#[test] fn` per fixture.
use std::env;
use std::fs;
use std::path::Path;

fn main() {
    // Rerun if any fixture changes
    let fixtures_dir = Path::new(&env::var("CARGO_MANIFEST_DIR").unwrap())
        .parent()
        .unwrap()
        .join("tests");
    println!("cargo:rerun-if-changed={}", fixtures_dir.display());

    let out_dir = env::var("OUT_DIR").unwrap();
    let dest_path = Path::new(&out_dir).join("generated_tests.rs");

    let mut test_fns = String::new();

    // Discover .test.npcs files
    if let Ok(entries) = fs::read_dir(&fixtures_dir) {
        for entry in entries.flatten() {
            let path = entry.path();
            if path.extension().map_or(false, |_ext| {
                let name = path.file_name().unwrap().to_string_lossy();
                name.ends_with(".test.npcs")
            }) {
                let file_name = path.file_name().unwrap().to_string_lossy().to_string();
                let fn_name = file_name
                    .replace(".test.npcs", "")
                    .replace(['-', '.'], "_")
                    .to_lowercase();

                // Use an absolute path for include_str!
                let abs_path = path.to_string_lossy().to_string();

                test_fns.push_str(&format!(
                    r#"
#[test]
fn generated_{fn_name}() {{
    let source = include_str!("{abs_path}");
    let result = npcs::cross_engine::run_test_source(source, "{file_name}");

    match result {{
        Ok(r) => {{
            if !r.passed {{
                let failures: Vec<String> = r.steps
                    .iter()
                    .filter(|s| !s.passed)
                    .flat_map(|s| s.failures.clone())
                    .collect();
                panic!(
                    "{{}} FAILED ({{}}ms):\n{{}}",
                    r.file_name,
                    r.total_time_ms,
                    failures.join("\n"),
                );
            }}
            // Verify timing
            for step in &r.steps {{
                assert!(
                    step.execution_time_ms < step.timeout_ms,
                    "Step exceeded timeout: {{}}ms",
                    step.execution_time_ms,
                );
            }}
        }}
        Err(e) => panic!("Error running {{}}: {{}}", "{file_name}", e),
    }}
}}
"#,
                ));
            }
        }
    }

    // Generate the module
    let code = format!(
        r#"// Auto-generated by build.rs — do not edit.
// Contains one test per .test.npcs fixture in tests/

{test_fns}
"#
    );

    fs::write(&dest_path, code).unwrap();

    // Tell Cargo where the generated file is
    println!("cargo:rustc-cfg=generated_tests");
}
