"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.CharacterCode = void 0;
var CharacterCode;
(function (CharacterCode) {
    CharacterCode[CharacterCode["WHITESPACE"] = 32] = "WHITESPACE";
    CharacterCode[CharacterCode["QUOTE"] = 34] = "QUOTE";
    CharacterCode[CharacterCode["NUMBER_0"] = 48] = "NUMBER_0";
    CharacterCode[CharacterCode["NUMBER_1"] = 49] = "NUMBER_1";
    CharacterCode[CharacterCode["NUMBER_2"] = 50] = "NUMBER_2";
    CharacterCode[CharacterCode["NUMBER_3"] = 51] = "NUMBER_3";
    CharacterCode[CharacterCode["NUMBER_4"] = 52] = "NUMBER_4";
    CharacterCode[CharacterCode["NUMBER_5"] = 53] = "NUMBER_5";
    CharacterCode[CharacterCode["NUMBER_6"] = 54] = "NUMBER_6";
    CharacterCode[CharacterCode["NUMBER_7"] = 55] = "NUMBER_7";
    CharacterCode[CharacterCode["NUMBER_8"] = 56] = "NUMBER_8";
    CharacterCode[CharacterCode["NUMBER_9"] = 57] = "NUMBER_9";
    CharacterCode[CharacterCode["TAB"] = 9] = "TAB";
    CharacterCode[CharacterCode["NEW_LINE"] = 10] = "NEW_LINE";
    CharacterCode[CharacterCode["RETURN_LINE"] = 13] = "RETURN_LINE";
    CharacterCode[CharacterCode["SLASH"] = 47] = "SLASH";
    CharacterCode[CharacterCode["DOT"] = 46] = "DOT";
    CharacterCode[CharacterCode["EQUAL"] = 61] = "EQUAL";
    CharacterCode[CharacterCode["ASTERISK"] = 42] = "ASTERISK";
    CharacterCode[CharacterCode["CARET"] = 94] = "CARET";
    CharacterCode[CharacterCode["PERCENT"] = 37] = "PERCENT";
    CharacterCode[CharacterCode["COMMA"] = 44] = "COMMA";
    CharacterCode[CharacterCode["CURLY_BRACKET_LEFT"] = 123] = "CURLY_BRACKET_LEFT";
    CharacterCode[CharacterCode["CURLY_BRACKET_RIGHT"] = 125] = "CURLY_BRACKET_RIGHT";
    CharacterCode[CharacterCode["SQUARE_BRACKETS_LEFT"] = 91] = "SQUARE_BRACKETS_LEFT";
    CharacterCode[CharacterCode["SQUARE_BRACKETS_RIGHT"] = 93] = "SQUARE_BRACKETS_RIGHT";
    CharacterCode[CharacterCode["PARENTHESIS_LEFT"] = 40] = "PARENTHESIS_LEFT";
    CharacterCode[CharacterCode["PARENTHESIS_RIGHT"] = 41] = "PARENTHESIS_RIGHT";
    CharacterCode[CharacterCode["SEMICOLON"] = 59] = "SEMICOLON";
    CharacterCode[CharacterCode["HASH"] = 35] = "HASH";
    CharacterCode[CharacterCode["MINUS"] = 45] = "MINUS";
    CharacterCode[CharacterCode["PLUS"] = 43] = "PLUS";
    CharacterCode[CharacterCode["EXCLAMATION_MARK"] = 33] = "EXCLAMATION_MARK";
    CharacterCode[CharacterCode["AT_SIGN"] = 64] = "AT_SIGN";
    CharacterCode[CharacterCode["COLON"] = 58] = "COLON";
    CharacterCode[CharacterCode["ARROW_LEFT"] = 60] = "ARROW_LEFT";
    CharacterCode[CharacterCode["ARROW_RIGHT"] = 62] = "ARROW_RIGHT";
    CharacterCode[CharacterCode["LETTER_E"] = 69] = "LETTER_E";
    CharacterCode[CharacterCode["LETTER_e"] = 101] = "LETTER_e";
})(CharacterCode || (exports.CharacterCode = CharacterCode = {}));
