"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.Keyword = void 0;
var Keyword;
(function (Keyword) {
    Keyword["If"] = "if";
    Keyword["In"] = "in";
    Keyword["Or"] = "or";
    Keyword["And"] = "and";
    Keyword["Isa"] = "isa";
    Keyword["For"] = "for";
    Keyword["Not"] = "not";
    Keyword["New"] = "new";
    Keyword["End"] = "end";
    Keyword["EndFor"] = "end for";
    Keyword["EndWhile"] = "end while";
    Keyword["EndFunction"] = "end function";
    Keyword["EndIf"] = "end if";
    Keyword["Then"] = "then";
    Keyword["Else"] = "else";
    Keyword["Break"] = "break";
    Keyword["While"] = "while";
    Keyword["ElseIf"] = "else if";
    Keyword["Return"] = "return";
    Keyword["Function"] = "function";
    Keyword["Continue"] = "continue";
    Keyword["Repeat"] = "repeat";
})(Keyword || (exports.Keyword = Keyword = {}));
