"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.Operator = void 0;
var Operator;
(function (Operator) {
    Operator["Plus"] = "+";
    Operator["Asterisk"] = "*";
    Operator["Minus"] = "-";
    Operator["Slash"] = "/";
    Operator["Power"] = "^";
    Operator["Modulo"] = "%";
    Operator["LessThan"] = "<";
    Operator["GreaterThan"] = ">";
    Operator["LessThanOrEqual"] = "<=";
    Operator["GreaterThanOrEqual"] = ">=";
    Operator["NotEqual"] = "!=";
    Operator["Equal"] = "==";
    Operator["Or"] = "or";
    Operator["And"] = "and";
    Operator["Not"] = "not";
    Operator["Isa"] = "isa";
    Operator["AddShorthand"] = "+=";
    Operator["SubtractShorthand"] = "-=";
    Operator["MultiplyShorthand"] = "*=";
    Operator["DivideShorthand"] = "/=";
    Operator["PowerShorthand"] = "^=";
    Operator["ModuloShorthand"] = "%=";
    Operator["Member"] = ".";
    Operator["Assign"] = "=";
    Operator["EndOfLine"] = ";";
    Operator["EndOfFile"] = "<eof>";
    Operator["SliceSeparator"] = ":";
    Operator["Comma"] = ",";
    Operator["Escape"] = "\"";
    Operator["SLBracket"] = "[";
    Operator["SRBracket"] = "]";
    Operator["CLBracket"] = "{";
    Operator["CRBracket"] = "}";
    Operator["LParenthesis"] = "(";
    Operator["RParenthesis"] = ")";
    Operator["Reference"] = "@";
    Operator["New"] = "new";
})(Operator || (exports.Operator = Operator = {}));
